{
 "title": "Weather station",
 "tags": [
  "weather ",
  "humidity",
  "pressure",
  "temperature "
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Active sensors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{sensor!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estado Sensores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"home_sensors\", location!=\"\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Indoor temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg_over_time(temperature[5m])>5",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Air - Gases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 5 },
   "targets": [
    { "expr": "avg_over_time(ppm[5m])", "legendFormat": "air-5m" },
    { "expr": "avg_over_time(ppm[1h])", "legendFormat": "air-1h" }
   ]
  },
  {
   "title": "Sea Level Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "avg_over_time(pressure[5m]) / (1 - (880 / 44330))^5.255 >800 <1300",
     "legendFormat": "basic_raw"
    },
    {
     "expr": "last_over_time(pressure[5m]) \r\n* on() group_left()\r\n(\r\n  (\r\n    (last_over_time(temperature{environment=\"outdoor\"}[5m]) + 273.15)\r\n    / \r\n    (last_over_time(temperature{environment=\"outdoor\"}[5m]) + 273.15 - (0.0065 * 880))\r\n  ) \r\n  ^5.255\r\n) >800 <1300",
     "legendFormat": "complex_raw"
    }
   ]
  },
  {
   "title": "Indoor humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "avg_over_time((humidity > 5)[5m:])",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "expr": "avg_over_time((pressure > 850 < 1300)[5m:])",
     "legendFormat": "press-5m"
    },
    {
     "expr": "avg_over_time((pressure > 850 < 1300)[15d:])",
     "legendFormat": "press-15d"
    },
    {
     "expr": "avg_over_time((pressure > 850 < 1300)[90d:])",
     "legendFormat": "press-90d"
    }
   ]
  },
  {
   "title": "Air - Gases (stddev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 13 },
   "targets": [
    { "expr": "stddev_over_time(ppm[1h])", "legendFormat": "air-stddev" }
   ]
  }
 ]
}